### ISSUE TITLE
Přidat emoji klávesnici

### ISSUE THREAD

**Issue by KmanCZ** [KmanCZ/nush#6]
Rozchodí a udělá demo pro https://www.npmjs.com/package/emoji-picker-react

**Comment by Watcher2002** [comment]
Musel som použiť natívnych emojis, čo sa mi nepáči z toho dôvodu, že tí od Microsoftu sú škaredí :) a zároveň, ak si nastavíš na mobile jedného, tak na počítači bude vyzerať inak. Nenapadá ti ako by sa dali spraviť tak, že aj keby použijem napr. emojis od googlu a vypíšem ich ako text, tak to budú tí istí a nie platform-dependant?

**Comment by KmanCZ** [comment]
> Musel som použiť natívnych emojis, čo sa mi nepáči z toho dôvodu, že tí od Microsoftu sú škaredí :) a zároveň, ak si nastavíš na mobile jedného, tak na počítači bude vyzerať inak. Nenapadá ti ako by sa dali spraviť tak, že aj keby použijem napr. emojis od googlu a vypíšem ich ako text, tak to budú tí istí a nie platform-dependant?

To by šlo udělat pouze pokud si uděláš vlastní sadu emoji a to většina platforem dělá dost nehezky (např. twitter vezme části kde je emoji a ty nahradí img jejich emoji pomocí js). Máme tedy v podstatě jen 2 možnosti, necháme to jak to je, nebo si musíme použít nějakou jinou klávesnici co používá vlastní sadu ikon, což se mi taky moc nelíbí (nemůžeme to uložit jen jako znak). Já bych to nechal tak jak to je.

**Comment by Watcher2002** [comment]
> > Musel som použiť natívnych emojis, čo sa mi nepáči z toho dôvodu, že tí od Microsoftu sú škaredí :) a zároveň, ak si nastavíš na mobile jedného, tak na počítači bude vyzerať inak. Nenapadá ti ako by sa dali spraviť tak, že aj keby použijem napr. emojis od googlu a vypíšem ich ako text, tak to budú tí istí a nie platform-dependant?
> 
> To by šlo udělat pouze pokud si uděláš vlastní sadu emoji a to většina platforem dělá dost nehezky (např. twitter vezme části kde je emoji a ty nahradí img jejich emoji pomocí js). Máme tedy v podstatě jen 2 možnosti, necháme to jak to je, nebo si musíme použít nějakou jinou klávesnici co používá vlastní sadu ikon, což se mi taky moc nelíbí (nemůžeme to uložit jen jako znak). Já bych to nechal tak jak to je.

Čakal som, že tam bude nejaký takýto problém, holt nebudú najkrajší :)

**Comment by KmanCZ** [comment]
> > > Musel som použiť natívnych emojis, čo sa mi nepáči z toho dôvodu, že tí od Microsoftu sú škaredí :) a zároveň, ak si nastavíš na mobile jedného, tak na počítači bude vyzerať inak. Nenapadá ti ako by sa dali spraviť tak, že aj keby použijem napr. emojis od googlu a vypíšem ich ako text, tak to budú tí istí a nie platform-dependant?
> > 
> > 
> > To by šlo udělat pouze pokud si uděláš vlastní sadu emoji a to většina platforem dělá dost nehezky (např. twitter vezme části kde je emoji a ty nahradí img jejich emoji pomocí js). Máme tedy v podstatě jen 2 možnosti, necháme to jak to je, nebo si musíme použít nějakou jinou klávesnici co používá vlastní sadu ikon, což se mi taky moc nelíbí (nemůžeme to uložit jen jako znak). Já bych to nechal tak jak to je.
> 
> Čakal som, že tam bude nejaký takýto problém, holt nebudú najkrajší :)

Ještě můžu vzít na prezentaci svůj macbook a odprezentujeme to na něm, tam jsou emoji hezké :)
